"""Desempacotamento de listas em Python"""


"""
OBS: PARA SELECIONAR UM ELEMENTO DA LISTA BASTA DECLARAR UMA VARIAVEL DE ACORDO COM O NÚMERO DE ELEMENTO QUE TEM NA LISTA 

SE VOCÊ QUISER PEGAR TODOS OS ELEMENTOS E JOGAR DENTRO DE UMA VARIAVEL BASTA USAR "*" 

DEPOIS QUE VOCÊ DECLARAR UMA VARIAVEL COM "*" QUALQUER VARIAVEL QUE FOR DECLARADA DEPOIS DELA PEGARÁ OS ULTIMOS INDICES DA LISTA

INFORMAÇÕES IMPORTANTES: SE VOCÊ DECLARAR UMA VARIAVELL "*_" INDICA QUE VOCÊ NÃO IRÁ USAR ELA NO RESTANTE DO CÓDIGO

"""

lista = ['Luiz', 'João', 'Maria', 1, 2, 3, 4, 5, 6, 7, 8]

n1, n2, *_, penultime_lista, ultimo_lista = lista

print(penultime_lista)


